### ISSUE TITLE
[HIPIFY][Issue] ERROR when build HIPIFY using Rocm's LLVM 

### ISSUE THREAD

**Issue by Lookforworld** [ROCm-Developer-Tools/HIPIFY#1499] opened 2024-05-13 02:23 UTC
### Problem Description

When I build HIPIFY using rocm6.1.1, I set the LLVM's path point to the '/opt/rocm-6.1.1/lib/llvm', but throw an error：
"
Could not find a package configuration file provided by "Clang" with any of
  the following names:
    ClangConfig.cmake
    clang-config.cmake
"
When i build the llvm myself, the file 'ClangConfig.cmake' is in the 'lib/cmake/clang/', but when i using rocm's llvm, the path 'opt/rocm/llvm/lib/cmake' no such file.

What should I do？

### Operating System

Ubuntu 22.04.4 LTS

### CPU

i5

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.1.0

### ROCm Component

ROCm

**Comment by emankov** [comment] 2024-05-23 16:13
HI @Lookforworld, Could you please provide the full log of hipify-clang's CMake and Make command lines?

**Comment by ppanchad-amd** [comment] 2024-08-10 17:31
@Lookforworld Do you still need assistance with this issue? If not, please close the ticket. Thanks!

**Comment by emankov** [comment] 2024-09-10 12:33
Most likely, the path to LLVM was specified incorrectly.
Based on the info provided in the ticket and [HIPIFY usage documentation]( https://github.com/ROCm/HIPIFY/blob/amd-staging/docs/hipify-clang.rst#usage), clang should be specified differently, for instance:

`--clang-resource-directory=/opt/rocm-6.1.1/lib/clang/18`

So, closing this ticket as `not a bug`.

**Closed as completed by emankov** 2024-09-10 12:33 UTC
Labels: clang, build, not a bug, failure
