### ISSUE TITLE
[HIPIFY][perl] Unsupported device function int_as_float/float_as_int

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIPIFY#501] opened 2022-02-18 23:35 UTC
Hipify (i.e. hipconvertinplace-perl.sh) shows the message unsupported device function "int_as_float"/"float_as_int" when converting a CUDA program. but __int_as_float/__float_as_int are supported by HIP.

We may just ignore the warning.

Thanks.

**Comment by emankov** [comment] 2022-02-19 19:38
Duplicate of #498.

**Comment by emankov** [comment] 2022-06-10 17:05
Fixed with #567.

**Closed as completed by emankov** 2022-06-10 17:05 UTC
Labels: bug, perl
