### ISSUE TITLE
[HIPIFY] hipconvertinplace-perl.sh does not seem to convert cuFuncSetAttribute and cuFuncSetCacheConfig

### ISSUE THREAD

**Issue by HannoSpreeuw** [ROCm-Developer-Tools/HIPIFY#1437] opened 2024-04-10 15:00 UTC
### Problem Description

I ran `hipconvertinplace-perl.sh .` from ROCm 5.7.1 on a CUDA codebase, but `cuFuncSetAttribute` was not converted into `hipFuncSetAttribute` and `cuFuncSetCacheConfig` was not converted into `hipFuncSetCacheConfig`; they remained unaltered.

### Operating System

NAME="Rocky Linux" VERSION="8.7 (Green Obsidian)"

### CPU

AMD EPYC 7F72 24-Core Processor

### GPU

AMD Radeon Pro W6800

### ROCm Version

ROCm 5.7.1

### ROCm Component

HIP

### Steps to Reproduce

Run `hipconvertinplace-perl.sh .` on a CUDA code base with calls to `cuFuncSetAttribute` and to `cuFuncSetCacheConfig`.

### Additional Information

No GPU needed to reproduce this issue.

**Comment by emankov** [comment] 2024-04-10 15:23
That's correct behaviour, as CUDA Driver APIs `cuFuncSetAttribute` and `cuFuncSetCacheConfig` are not supported by HIP yet; only their CUDA Runtime analogues `cudaFuncSetAttribute` and `cudaFuncSetCacheConfig` are supported.

HIPIFY tools should have warned about all unsupported APIs found in the CUDA source text.

**Comment by emankov** [comment] 2024-04-10 15:24
Closing it as not a bug.

**Closed as completed by emankov** 2024-04-10 15:24 UTC
Labels: perl, not a bug
