### ISSUE TITLE
[HIPIFY][clang][bug] Clang doesn't fully support variadic functions

### ISSUE THREAD

**Issue by ZenggangLiu** [ROCm-Developer-Tools/HIPIFY#629] opened 2022-09-02 05:39 UTC
I just updated all llvm and hipify source trees and compiled hipify using c++17 standard.
everything went well.

But when I start porting my kernels and using the default cuda 11.7 sdk,
at first i will see: 
```CUSTOMBUILD : warning : CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version] ```

then it just throws out some complains on the variadic functions:
```
  In file included from C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/include\cuda/std/type_traits:24:
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/include\cuda/std/detail/libcxx/include/type_traits(520,12): error G3E10ACFB: CUDA device code does not support variadic functions [D:\Repository\HIP\build\MatPreview\HIP_File.vcxproj]
  false_type __sfinae_test_impl(...);
                 ^
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/include\cuda/std/detail/libcxx/include/type_traits(1059,69): error G3E10ACFB: CUDA device code does not support variadic functions [D:\Repository\HIP\build\MatPreview\HIP_File.vcxproj]
      template <class _Tp> _LIBCUDACXX_INLINE_VISIBILITY static __two __test(...);
                                                                                                              ^
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/include\cuda/std/detail/libcxx/include/type_traits(1175,5): error G3E10ACFB: CUDA device code does not support variadic functions [D:\Repository\HIP\build\MatPreview\HIP_File.vcxproj]
      __any(...);
      ^
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/include\cuda/std/detail/libcxx/include/type_traits(1852,16): error G3E10ACFB: CUDA device code does not support variadic functions [D:\Repository\HIP\build\MatPreview\HIP_File.vcxproj]
     static void __test(...);
                     ^
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7/include\cuda/std/detail/libcxx/include/type_traits(4336,16): error G3E10ACFB: CUDA device code does not support variadic functions [D:\Repository\HIP\build\MatPreview\HIP_File.vcxproj]
    static __nat __try_call(...);
                      ^
```
clang and llvm versions are:
clang -cc1 version 16.0.0 based upon LLVM 16.0.0git default target x86_64-pc-windows-msvc
clang version 16.0.0 (https://github.com/RadeonOpenCompute/llvm-project.git 610c70d52c80790b4876988a357198d9b2cc8102)
please help me out

Thanks a lot

**Comment by emankov** [comment] 2022-09-02 09:59
@ZenggangLiu,

1. CUDA 11.7.x is supported by hipify-clang (its own unit testing pass on the latest CUDA and trunk LLVM)
2. hipify-clang has been switched to C++17 this week but only for ToT LLVM (16.0.0git) - there is no need for the user to specify the C++ standard explicitly
3. Don't worry about the warning `CUDA version is newer than the latest supported version 11.5` - it is just clang says that the latest officially supported version is 11.5, but actually, all the further CUDA versions are supported.
4. As for your compilation errors, I need your source CUDA file(s) to look into

**Comment by ZenggangLiu** [comment] 2022-09-05 00:34
thank you very much for checking this on your side.
i still have the same issue, when hipifying the following testing kernel:
```
// CUDA kernel. Each thread takes care of one element of c
#include <cooperative_groups.h>


extern "C"
__global__ void vecAdd(float *a, float *b, float *c, int n)
{
    // Get our global thread ID
    int id = blockIdx.x*blockDim.x+threadIdx.x;
 
    // Make sure we do not go out of bounds
    if (id < n)
        c[id] = a[id] + b[id];
}
```
the errors are in one of the include within ```cooperative_groups.h```: ```type_traits```.
I double checked that using the master branch of hipify at commit hashing ```89a79e6297d4cad16f77f1c3565216e1164bc93a```
and llvm is using its ```adm-stg-open``` branch at commit hashing ```610c70d52c80790b4876988a357198d9b2cc8102```

**Comment by emankov** [comment] 2022-09-05 10:13
Could you please provide the complete hipify-clang log including its command line populated with the `-v` (verbose) option?

**Comment by ZenggangLiu** [comment] 2022-09-05 22:48
Please find the command line I used and the log file HIPIFY generated in the attachment
Thank you very much for the helps
[HIPIFY_Release_Build_Logs.zip](https://github.com/ROCm-Developer-Tools/HIPIFY/files/9492238/HIPIFY_Release_Build_Logs.zip)
[HIPIFY_Command_Line.txt](https://github.com/ROCm-Developer-Tools/HIPIFY/files/9492239/HIPIFY__Command_Line.txt)

**Comment by emankov** [comment] 2022-09-07 13:24
Hello @ZenggangLiu,

Well, I looked into the logs. I see, you are using hipify on Windows and you are running INSTALL from its solution (undocumented feature). I did the same on Windows with ToT hipify, ToT LLVM, and CUDA 11.7 Update 1. It looks like everything is fine from your side. The problem is on LLVM/clang side. Actually, it is known problem with CUDA variadic functions support in clang.

Please, add clang  `-- -Xclang -fcuda-allow-variadic-functions` at the end of hipify-clang's command line.

**Comment by emankov** [comment] 2022-09-16 14:37
Closing as answered

**Closed as completed by emankov** 2022-09-16 14:37 UTC
Labels: bug, clang

**Comment by fxmarty** [comment] 2023-06-30 06:03
> Don't worry about the warning CUDA version is newer than the latest supported version 11.5 - it is just clang says that the latest officially supported version is 11.5, but actually, all the further CUDA versions are supported.

There should not be this warning then?
