### ISSUE TITLE
[HIPIFY] I accomplish HIP code to CUDA code reference Hipify, but meet some error when I run code by cuda_runtime_api.h

### ISSUE THREAD

**Issue by wangzy0327** [ROCm-Developer-Tools/HIPIFY#466] opened 2021-12-08 08:10 UTC
![image](https://user-images.githubusercontent.com/22990858/145747144-90638faf-e14e-4dba-8df3-ca44fe43eaf3.png)
![image](https://user-images.githubusercontent.com/22990858/145750755-9df8246b-4f52-4e7c-8893-ee648f49e2c4.png)

this is my github link about cudify:
https://github.com/wangzy0327/Hip-conversion

**Comment by emankov** [comment] 2021-12-08 08:39
Hi @wangzy0327,

So, you converted HIP to CUDA (not vice versa) and tried to compile the resulting CUDA source (by what?), got errors, and decided to file an issue to HIPIFY tools? What do you want from the HIPIFY team?

**Comment by wangzy0327** [comment] 2021-12-10 08:24
Sorry,I cannot describe it clearly. 
I compile the resulting CUDA source by regular expression reference hipify-perl.
I want to know the limitations of conversion by regular expression. ep hipify-perl(what contents cannot convert?)

**Comment by emankov** [comment] 2021-12-11 16:42
Well, you may provide both your source files. From the last screenshot, it looks like you are mixing CUDA and HIP APIs in your CUDA source.

**Comment by wangzy0327** [comment] 2021-12-13 03:24
Yes,I fix some bugs in my code.
This is my test source files
https://github.com/zjin-lcf/HeCBench/blob/master/atomicCAS-hip/main.cu
https://github.com/zjin-lcf/HeCBench/blob/master/atomicCAS-cuda/main.cu

And convert file code and execute results
![1639365826(1)](https://user-images.githubusercontent.com/22990858/145747522-9d139205-3610-472e-8848-ec0cc54cce9a.jpg)

**Comment by emankov** [comment] 2021-12-18 17:01
I've successfully hipified your [atomicCAS-cuda](https://github.com/zjin-lcf/HeCBench/blob/master/atomicCAS-cuda/main.cu) to HIP both by `hipify-perl` and `hipify-clang`. The HIP source obtained by `hipify-clang` is identical to your [atomicCAS-hip](https://github.com/zjin-lcf/HeCBench/blob/master/atomicCAS-hip/main.cu).

Both [atomicCAS-cuda](https://github.com/zjin-lcf/HeCBench/blob/master/atomicCAS-cuda/main.cu) and [atomicCAS-hip](https://github.com/zjin-lcf/HeCBench/blob/master/atomicCAS-hip/main.cu) was successfully compiled by `hipcc`.

The segfault you got when running `atomicCAS-hip` can happen for many reasons.

[Conclusions]
1. The issue is not related to HIPIFY tools.
2. You may file an issue to the [HIP](https://github.com/ROCm-Developer-Tools/HIP) repo by providing your core dump log and info about ROCm HIP installed.
3. This issue is closing as unrelated.

**Closed by emankov** 2021-12-18 17:01 UTC
Labels: not a bug
